### ISSUE TITLE
IoDriver for L298N ?

### ISSUE THREAD

**Issue by hsh001** [Wallacoloo/printipi#90]
Hi
Does anyboby works on minimalist cnc using L298N as driver for bipolar stepper motors ?
With this 'dual full bridge' motor direction is handling by a simple step inversion...
It will be nice to use printipi for a very simple cnc...
Thanks for your job

**Comment by Wallacoloo** [comment]
Hi @hsh001. There is currently no built-in support for L298N drivers. However, if you wish to add support for it, you can create a new file, src/iodrivers/L298N.h, implement the same interface as in [src/iodrivers/stepdirstepperdriver.h](https://github.com/Wallacoloo/printipi/blob/master/src/iodrivers/stepdirstepperdriver.h) and then use the L298N type in place of A4988 in your machine configuration file.

The `getEventOutputSequence` function is called every time the motion planner plans a step. It is (naively) expected to be 'const', but any dual full-bridge implementation will likely have to be stateful, since the signals needed to move a stepper by +/- 1 step are dependent upon the current step number (mod 4, I believe). This isn't a problem - just declare the necessary state info as `mutable`, and keep the method `const`.

You can also change the return type to (e.g.) `std::array<OutputEvent, 2>`, since I believe advancing one step using a dual full-bridge should only require toggling two outputs
