### ISSUE TITLE
Cannot Connect To Printer Ussing octoPrint

### ISSUE THREAD

**Issue by mohamedamineamdouni** [Wallacoloo/printipi#92]
Changing monitoring state from 'Offline' to 'Opening serial port'
Connecting to: None
Unexpected error while connecting to serial port: None OSError: '[Errno 2] No such file or directory: 'None'' @ comm.py:_openSerial:943
Changing monitoring state from 'Opening serial port' to 'Error: Failed to open serial port, permissions correct?'
Changing monitoring state from 'Offline' to 'Opening serial port'
Connecting to: None
Unexpected error while connecting to serial port: None OSError: '[Errno 2] No such file or directory: 'None'' @ comm.py:_openSerial:943
Changing monitoring state from 'Opening serial port' to 'Error: Failed to open serial port, permissions correct?
i make chmod -l 777 /dev/ttyUSBprintipi
but still don't work

**Comment by Wallacoloo** [comment]
You haven't provided much detail as to what you did to trigger the error, but at a glance this _appears_ to be an issue on Octoprint's side.

The standard device naming for serial ports is `/dev/ttyAMA0`, `/dev/ttyAMA1`, or `/dev/ttyUSB0`, `/dev/ttyUSB1` (for serial-over-USB devices), ....

Since the "serial port" that Printipi uses for communication is entirely virtual, I elected to use a different naming scheme. It's possible that since then, Octoprint has introduced code that breaks when trying to connect to a serial port with a non-standard name, so you might try renaming it to something like `/dev/ttyUSB0` and trying that. You can probably just `sudo mv /dev/ttyUSBprintipi /dev/ttyUSB0`.
